version: '3.8'
services:
  db:
    image: docker.io/library/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./db/mysql:/var/lib/mysql
  adminer:
    image: docker.io/library/adminer:latest
    restart: always
    ports: "8081:8080"
    depends_on:
      - db
  backend:
    build: ./backend
    ports: "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports: "4200:4200"
    depends_on:
      - backend
